name: Test
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: expected-screenshots.zip
          path: screenshots/*.png
      - name: Install modules
        run: npm install
      - name: Run tests
        id: test
        run: npm run test
        continue-on-error: true
      - uses: actions/upload-artifact@v3
        with:
          name: actual-screenshots.zip
          path: screenshots/*.png

      - name: Update Coverage Badge
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main
      - name: Fail workflow if tests failed
        if: steps.test.outcome == 'failure'
        run: exit 1
